FROM node:20.6-alpine3.17

ENV NODE_ENV development

WORKDIR /usr/server

COPY package*.json ./
COPY tsconfig.json ./
COPY .env ./
COPY ./src ./
# RUN npm install
RUN yarn install

EXPOSE 10500
# CMD [ "npm", "start", "dev" ]
# CMD ["node", "src/index.js"]
# CMD ["yarn", "dev"]
CMD ["yarn", "nodemon", "src/index.ts"]
